[package]
name = "VCBPlus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
byteorder = "1.4.3"
enum_primitive = "0.1.1"
pretty = "0.12.0"
zstd = "0.12.3"
